version: '3'
services:
  mlflow:
    image: mlflow
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000
    networks:
      - airflow-mlflow-network

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile-airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW_CONN_DATAHUB_REST_DEFAULT=http://datahub:8080
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./datasets:/opt/airflow/datasets
      - ./models:/opt/airflow/models
    ports:
      - "8080:8080"
    command: bash -c "
      airflow db init &&
      airflow users create --username admin --firstname Admin --lastname User --role Admin --password admin --email admin@example.com &&
      airflow db upgrade &&
      airflow webserver
      "
    depends_on:
      - postgres
      - mlflow
    networks:
      - airflow-mlflow-network

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile-airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW_CONN_DATAHUB_REST_DEFAULT=http://datahub:8080
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./datasets:/opt/airflow/datasets
      - ./models:/opt/airflow/models
    command: bash -c "airflow db upgrade && airflow scheduler"
    depends_on:
      - postgres
      - airflow-webserver
      - mlflow
    networks:
      - airflow-mlflow-network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - airflow-mlflow-network

volumes:
  postgres-db-volume:

networks:
  airflow-mlflow-network:
    driver: bridge